### ISSUE TITLE
using 0.1.9 version and plugin set local file system cant read hap file

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#11] opened 2019-03-02 01:02 UTC
you can see this video, i dont know why. hap1 file this your github assets file.

[Video_1.zip](https://github.com/keijiro/KlakHap/files/2921576/Video_1.zip)

**Comment by fingerx** [comment] 2019-03-02 01:21
I have repeatedly operated it again and again and it can be loaded normally. It feels very strange. I do not know why. I have met several times.

**Comment by keijiro** [comment] 2019-03-02 10:15
This might be another editor related issue. I think this only affects UI; The warning message will be gone if you start play mode. So I recommend ignoring the message and starting play mode when you meet this issue.

Please let me know if you find a way to reproduce the issue. This should be fixed even if it's UI-only issue.

**Comment by keijiro** [comment] 2019-03-07 23:17
I'm closing this issue because it can't reproduce on my side. Please feel free to reopen if you find a way to reproduce the issue on the latest version.

**Closed by keijiro** 2019-03-07 23:17 UTC
Labels: question
