### ISSUE TITLE
play hap video is ok but cannot hear the sound

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#8] opened 2019-02-24 07:25 UTC
Hello，using klakhap play hap video is ok but cant hear the sound.I use vlc and everything works fine. Is what I missed? thanks

**Comment by keijiro** [comment] 2019-02-24 11:46
KlakHap doesn't support audio. There is no plan for adding audio support at the moment. I thought that it doesn't need audio playback in most use case of the HAP codec.

Just out of curiosity, what do you think about it? What are you going to use it for?

**Comment by fingerx** [comment] 2019-02-24 12:08
Play large resolution videos. Because video and audio are the final output for a file. Is there any way to make the audio drive video play?

**Comment by keijiro** [comment] 2019-02-24 12:20
I thought that people would use the default VideoPlayer component just for playing videos, even if it's large resolution. HAP is only useful when precise frame control is needed (for example, VJing, SFX/VFX, etc.), and audio playback is not so important in these cases.

**Comment by fingerx** [comment] 2019-02-24 12:40
thank you very much. You write precise frame control. If I calculate the playback frame index of the audio, I play it by setting the frame index of the video. Is this ok? Audio is very important to me, I hope you can give me some advice. Thanks again.

**Comment by fingerx** [comment] 2019-02-24 13:37
@keijiro Can you tell me the unit of streamDuration? I am very confused. I have a video showing 8 minutes and 14 seconds in vlc, but the stream duration in the plugin shows 51.3

**Comment by fingerx** [comment] 2019-02-24 13:49
![image](https://user-images.githubusercontent.com/5524551/53300119-c5ac9480-387d-11e9-9082-a0123a314314.png)
![image](https://user-images.githubusercontent.com/5524551/53300143-10c6a780-387e-11e9-9c0e-fa728f3f3d8f.png)

**Comment by keijiro** [comment] 2019-02-25 01:59
It's shown in seconds. So, it seems to fail to analyze the video file. Could you provide this file or another file that can reproduce the issue? I'd like to look into it.

**Comment by fingerx** [comment] 2019-02-25 03:53
@keijiro  thanks.I found the reason. If one frame is missing from the video synthesized by the sequence frame, the plugin will only read the file before the missing frame, so this time will be wrong. My file is very large（134GB）. I also found a bug and didn't know why. I synthesized a complete video through a sequence of frames, but the plugin did not recognize it.
The composition command is as follows: 
ffmpeg -r 30 -f image2 -s 6208x2304 -i D:\Download\Frames\0612\frontend\front%05d.jpg -i D:\TestVideo\audio.wav -format hapq -chunks 4 -compressor None -acodec copy OUTPUT.mov

Screenshot below:
![snipaste_2019-02-25_11-46-33](https://user-images.githubusercontent.com/5524551/53313338-ee6f7100-38f3-11e9-9878-0b68ab0b5d31.png)
![snipaste_2019-02-25_11-46-48](https://user-images.githubusercontent.com/5524551/53313346-f4655200-38f3-11e9-83b5-282ba25eae88.png)

**Comment by keijiro** [comment] 2019-02-25 05:17
Okay. I'll try to reproduce the issue with missing frames on my side. At the moment, I'd recommend working around the issue by filling missing frames with neighbor frames.

**Comment by keijiro** [comment] 2019-02-25 08:32
I couldn't reproduce the issue because ffmpeg stops reading an image sequence when it founds a missing frame. How do you create the file with missing frames? Or could you provide another small file that can reproduce the issue?

**Comment by fingerx** [comment] 2019-02-25 12:48
this test frames and mov file:
https://drive.google.com/open?id=1OkyJU8IA1o1-RcLA2iT43LPcTpjpn7hm

I don't know why I can't reproduce this problem, because there is a new problem, the plugin can't recognize the format, but vlc can recognize it as hap

![image](https://user-images.githubusercontent.com/5524551/53338267-3adf9e80-393e-11e9-84e1-d57508becb29.png)


In addition, I think this can't be called a bug, which is the wrong resource for human negligence.

**Comment by fingerx** [comment] 2019-02-25 12:49
@keijiro  thanks,I closed this . This is my problem. Thanks again.

**Comment by fingerx** [comment] 2019-02-25 14:14
extra information:
You can try to change the video file suffix, and then change the file name. The plugin will have time normal and sometimes it is not normal. The reading of the file should be independent of the suffix, just like other regular players, such as vlc

**Comment by fingerx** [comment] 2019-02-25 16:13
info2：

using streamingassets path mode all is ok but using local file path mode sometimes not normal

**Comment by keijiro** [comment] 2019-02-26 03:21
I couldn't reproduce the issue. The plugin doesn't use any information with the file suffix, so I hardly think it causes any issue by changing the file suffix.

Could you please re-check if it actually reproduces?

**Comment by fingerx** [comment] 2019-02-26 04:03
@keijiro please see images and test project,thanks(this project using your github code and video)

![image](https://user-images.githubusercontent.com/5524551/53386629-f1cf2f00-39bd-11e9-924b-74166025d078.png)
![image](https://user-images.githubusercontent.com/5524551/53386638-f72c7980-39bd-11e9-8b0e-4c012f2d8395.png)
![image](https://user-images.githubusercontent.com/5524551/53386649-014e7800-39be-11e9-9d12-41528e52b5a9.png)

[KlakHapTest.zip](https://github.com/keijiro/KlakHap/files/2903711/KlakHapTest.zip)

**Comment by fingerx** [comment] 2019-02-26 04:16
add test video(please using vlc play):
[record.zip](https://github.com/keijiro/KlakHap/files/2903742/record.zip)

**Comment by fingerx** [comment] 2019-02-26 04:32
@keijiro  add test2 can easy see this error.
[Video_test2.zip](https://github.com/keijiro/KlakHap/files/2903794/Video_test2.zip)

**Comment by keijiro** [comment] 2019-02-26 05:32
It seems to be another bug: The inspector shows "Failed to open file" error when clicking a path mode item without changing the selection. It just shows a wrong error message, so you can safely ignore it. I'll try fixing it later. Please ignore this error message until it gets fixed.

**Comment by keijiro** [comment] 2019-02-26 05:49
Fixed: https://github.com/keijiro/KlakHap/releases/tag/v0.1.8

**Comment by fingerx** [comment] 2019-02-26 06:07
@keijiro update v0.18 test is ok,thanks very much

**Comment by keijiro** [comment] 2019-02-26 12:46
I'm closing this issue now. Please feel free to reopen again for further questions.

**Closed by keijiro** 2019-02-26 12:46 UTC
Labels: question
